version: "2"

linters:
  default: standard
  enable:
    - bodyclose
    - misspell
  settings:
    govet:
      enable:
        - shadow

formatters:
  enable:
    - gofmt
    - gofumpt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/nyaungnicholas-wq/tickstream
